[project]
name = "emissary_backend"
version = "0.1.0"
description = "Backend for the Emissary"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-generativeai>=0.8.3",
    "sunholo[gcp,http]>=0.115.2",
]

[tool.uv.sources]
sunholo = { git = "https://github.com/sunholo-data/sunholo-py" }
